permissions:
  contents: read
  id-token: write
  pages: write

on:
  push:
    branches:
      - main

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.2
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - run: |
          cargo build --release
          npm ci
          npm run build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist
      - id: deploy
        uses: actions/deploy-pages@v1
